from PyQt6.QtGui import QPixmap, QIcon
from PyQt6.QtWidgets import *
from database import SessionLocal, init_db
from services.book_service import BookService


class AssortmentWin(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setGeometry(370, 100, 450, 870)
        self.setFixedSize(self.width(), self.height())
        self.setWindowIcon(QIcon('logo_pictures/window_icon.png'))
        self.setWindowTitle('Ассортимент')

        self.label1 = QLabel()
        self.label2 = QLabel()
        self.label3 = QLabel()
        self.label4 = QLabel()
        self.label5 = QLabel()
        self.label6 = QLabel()

        self.name_label1 = QLabel()
        self.name_label2 = QLabel()
        self.name_label3 = QLabel()
        self.name_label4 = QLabel()
        self.name_label5 = QLabel()
        self.name_label6 = QLabel()

        self.pixmap = QPixmap()

        self.page_btn1 = QPushButton('1')
        self.page_btn1.setFixedSize(25, 25)
        self.page_btn1.clicked.connect(self.button_click1)
        self.page_btn2 = QPushButton('2')
        self.page_btn2.setFixedSize(25, 25)
        self.page_btn2.clicked.connect(self.button_click2)
        self.page_btn3 = QPushButton('3')
        self.page_btn3.setFixedSize(25, 25)
        self.page_btn3.clicked.connect(self.button_click3)
        self.page_btn4 = QPushButton('4')
        self.page_btn4.setFixedSize(25, 25)
        self.page_btn4.clicked.connect(self.button_click4)
        self.page_btn5 = QPushButton('5')
        self.page_btn5.setFixedSize(25, 25)
        self.page_btn5.clicked.connect(self.button_click5)
        self.page_btn6 = QPushButton('6')
        self.page_btn6.setFixedSize(25, 25)
        self.page_btn6.clicked.connect(self.button_click6)
        self.page_btn7 = QPushButton('7')
        self.page_btn7.setFixedSize(25, 25)
        self.page_btn7.clicked.connect(self.button_click7)

        self.page_label = QLabel()

        init_db()
        db = SessionLocal()

        self.book_service = BookService(db)

        self.button_click1()

        main_l = QVBoxLayout()
        h_l1 = QHBoxLayout()
        hl1_name = QHBoxLayout()
        h_l2 = QHBoxLayout()
        hl2_name = QHBoxLayout()
        h_l3 = QHBoxLayout()
        hl3_name = QHBoxLayout()
        hl_pages = QHBoxLayout()
        hl_page_label = QHBoxLayout()
        h_l1.addWidget(self.label1)
        h_l1.addWidget(self.label2)
        hl1_name.addWidget(self.name_label1)
        hl1_name.addWidget(self.name_label2)
        h_l2.addWidget(self.label3)
        h_l2.addWidget(self.label4)
        hl2_name.addWidget(self.name_label3)
        hl2_name.addWidget(self.name_label4)
        h_l3.addWidget(self.label5)
        h_l3.addWidget(self.label6)
        hl3_name.addWidget(self.name_label5)
        hl3_name.addWidget(self.name_label6)
        hl_pages.addWidget(self.page_btn1)
        hl_pages.addWidget(self.page_btn2)
        hl_pages.addWidget(self.page_btn3)
        hl_pages.addWidget(self.page_btn4)
        hl_pages.addWidget(self.page_btn5)
        hl_pages.addWidget(self.page_btn6)
        hl_pages.addWidget(self.page_btn7)
        hl_page_label.addWidget(self.page_label)
        main_l.addLayout(h_l1)
        main_l.addLayout(hl1_name)
        main_l.addLayout(h_l2)
        main_l.addLayout(hl2_name)
        main_l.addLayout(h_l3)
        main_l.addLayout(hl3_name)
        main_l.addStretch()
        main_l.addLayout(hl_pages)
        main_l.addLayout(hl_page_label)
        self.setLayout(main_l)

    def button_click1(self):
        book1 = self.book_service.load_book(1)
        book2 = self.book_service.load_book(2)
        book3 = self.book_service.load_book(3)
        book4 = self.book_service.load_book(4)
        book5 = self.book_service.load_book(5)
        book6 = self.book_service.load_book(6)

        self.name_label1.setText(f'{book1[0]}\n{book1[1]}\n{book1[2]} руб.')
        self.name_label2.setText(f'{book2[0]}\n{book2[1]}\n{book2[2]} руб.')
        self.name_label3.setText(f'{book3[0]}\n{book3[1]}\n{book3[2]} руб.')
        self.name_label4.setText(f'{book4[0]}\n{book4[1]}\n{book4[2]} руб.')
        self.name_label5.setText(f'{book5[0]}\n{book5[1]}\n{book5[2]} руб.')
        self.name_label6.setText(f'{book6[0]}\n{book6[1]}\n{book6[2]} руб.')

        self.pixmap.load(book1[3])
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book2[3])
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book3[3])
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book4[3])
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book5[3])
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book6[3])
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn7.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 1')

    def button_click2(self):
        book1 = self.book_service.load_book(7)
        book2 = self.book_service.load_book(8)
        book3 = self.book_service.load_book(9)
        book4 = self.book_service.load_book(10)
        book5 = self.book_service.load_book(11)
        book6 = self.book_service.load_book(12)

        self.name_label1.setText(f'{book1[0]}\n{book1[1]}\n{book1[2]} руб.')
        self.name_label2.setText(f'{book2[0]}\n{book2[1]}\n{book2[2]} руб.')
        self.name_label3.setText(f'{book3[0]}\n{book3[1]}\n{book3[2]} руб.')
        self.name_label4.setText(f'{book4[0]}\n{book4[1]}\n{book4[2]} руб.')
        self.name_label5.setText(f'{book5[0]}\n{book5[1]}\n{book5[2]} руб.')
        self.name_label6.setText(f'{book6[0]}\n{book6[1]}\n{book6[2]} руб.')

        self.pixmap.load(book1[3])
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book2[3])
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book3[3])
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book4[3])
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book5[3])
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book6[3])
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn7.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 2')

    def button_click3(self):
        book1 = self.book_service.load_book(13)
        book2 = self.book_service.load_book(14)
        book3 = self.book_service.load_book(15)
        book4 = self.book_service.load_book(16)
        book5 = self.book_service.load_book(17)
        book6 = self.book_service.load_book(18)

        self.name_label1.setText(f'{book1[0]}\n{book1[1]}\n{book1[2]} руб.')
        self.name_label2.setText(f'{book2[0]}\n{book2[1]}\n{book2[2]} руб.')
        self.name_label3.setText(f'{book3[0]}\n{book3[1]}\n{book3[2]} руб.')
        self.name_label4.setText(f'{book4[0]}\n{book4[1]}\n{book4[2]} руб.')
        self.name_label5.setText(f'{book5[0]}\n{book5[1]}\n{book5[2]} руб.')
        self.name_label6.setText(f'{book6[0]}\n{book6[1]}\n{book6[2]} руб.')

        self.pixmap.load(book1[3])
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book2[3])
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book3[3])
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book4[3])
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book5[3])
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book6[3])
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn7.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 3')

    def button_click4(self):
        book1 = self.book_service.load_book(19)
        book2 = self.book_service.load_book(20)
        book3 = self.book_service.load_book(21)
        book4 = self.book_service.load_book(22)
        book5 = self.book_service.load_book(23)
        book6 = self.book_service.load_book(24)

        self.name_label1.setText(f'{book1[0]}\n{book1[1]}\n{book1[2]} руб.')
        self.name_label2.setText(f'{book2[0]}\n{book2[1]}\n{book2[2]} руб.')
        self.name_label3.setText(f'{book3[0]}\n{book3[1]}\n{book3[2]} руб.')
        self.name_label4.setText(f'{book4[0]}\n{book4[1]}\n{book4[2]} руб.')
        self.name_label5.setText(f'{book5[0]}\n{book5[1]}\n{book5[2]} руб.')
        self.name_label6.setText(f'{book6[0]}\n{book6[1]}\n{book6[2]} руб.')

        self.pixmap.load(book1[3])
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book2[3])
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book3[3])
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book4[3])
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book5[3])
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book6[3])
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn7.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 4')

    def button_click5(self):
        book1 = self.book_service.load_book(25)
        book2 = self.book_service.load_book(26)
        book3 = self.book_service.load_book(27)
        book4 = self.book_service.load_book(28)
        book5 = self.book_service.load_book(29)
        book6 = self.book_service.load_book(30)

        self.name_label1.setText(f'{book1[0]}\n{book1[1]}\n{book1[2]} руб.')
        self.name_label2.setText(f'{book2[0]}\n{book2[1]}\n{book2[2]} руб.')
        self.name_label3.setText(f'{book3[0]}\n{book3[1]}\n{book3[2]} руб.')
        self.name_label4.setText(f'{book4[0]}\n{book4[1]}\n{book4[2]} руб.')
        self.name_label5.setText(f'{book5[0]}\n{book5[1]}\n{book5[2]} руб.')
        self.name_label6.setText(f'{book6[0]}\n{book6[1]}\n{book6[2]} руб.')

        self.pixmap.load(book1[3])
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book2[3])
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book3[3])
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book4[3])
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book5[3])
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book6[3])
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn7.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 5')

    def button_click6(self):
        book1 = self.book_service.load_book(31)
        book2 = self.book_service.load_book(32)
        book3 = self.book_service.load_book(33)
        book4 = self.book_service.load_book(34)
        book5 = self.book_service.load_book(35)
        book6 = self.book_service.load_book(36)

        self.name_label1.setText(f'{book1[0]}\n{book1[1]}\n{book1[2]} руб.')
        self.name_label2.setText(f'{book2[0]}\n{book2[1]}\n{book2[2]} руб.')
        self.name_label3.setText(f'{book3[0]}\n{book3[1]}\n{book3[2]} руб.')
        self.name_label4.setText(f'{book4[0]}\n{book4[1]}\n{book4[2]} руб.')
        self.name_label5.setText(f'{book5[0]}\n{book5[1]}\n{book5[2]} руб.')
        self.name_label6.setText(f'{book6[0]}\n{book6[1]}\n{book6[2]} руб.')

        self.pixmap.load(book1[3])
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book2[3])
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book3[3])
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book4[3])
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book5[3])
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load(book6[3])
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn7.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 6')

    def button_click7(self):
        book1 = self.book_service.load_book(37)

        self.name_label1.setText(f'{book1[0]}\n{book1[1]}\n{book1[2]} руб.')
        self.name_label2.setText(f'-\n-\n- руб.')
        self.name_label3.setText(f'-\n-\n- руб.')
        self.name_label4.setText(f'-\n-\n- руб.')
        self.name_label5.setText(f'-\n-\n- руб.')
        self.name_label6.setText(f'-\n-\n- руб.')

        self.pixmap.load(book1[3])
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/book.jpg')
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/book.jpg')
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/book.jpg')
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/book.jpg')
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/book.jpg')
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn7.setStyleSheet('QPushButton {background-color: #A3C1DA}')

        self.page_label.setText('Текущая страница: 7')


def main():
    app = QApplication([])
    win = AssortmentWin()
    win.show()
    app.exec()


if __name__ == '__main__':
    main()
