from PyQt6.QtGui import QPixmap, QIcon
from PyQt6.QtWidgets import *


class AssortmentWin(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setGeometry(370, 100, 450, 870)
        self.setFixedSize(self.width(), self.height())
        self.setWindowIcon(QIcon('logo_pictures/window_icon.png'))
        self.setWindowTitle('Ассортимент')

        self.label1 = QLabel()
        self.label2 = QLabel()
        self.label3 = QLabel()
        self.label4 = QLabel()
        self.label5 = QLabel()
        self.label6 = QLabel()

        self.name_label1 = QLabel('Над пропастью во ржи\nДж. Д. Сэллинджер\n800 руб.')
        self.name_label2 = QLabel('1984\nДж. Оруэл\n1000 руб.')
        self.name_label3 = QLabel('Преступление и наказание\nФ. Достоевский\n1500 руб.')
        self.name_label4 = QLabel('Три товарища\nЭ. М. Ремарк\n400 руб.')
        self.name_label5 = QLabel('Приключения Гекльберри Финна\nМ. Твен\n1200 руб.')
        self.name_label6 = QLabel('Мёртвые Души\nН. Гоголь\n500 руб.')

        self.pixmap = QPixmap()

        self.page_btn1 = QPushButton('1')
        self.page_btn1.setFixedSize(25, 25)
        self.page_btn1.clicked.connect(self.button_click1)
        self.page_btn2 = QPushButton('2')
        self.page_btn2.setFixedSize(25, 25)
        self.page_btn2.clicked.connect(self.button_click2)
        self.page_btn3 = QPushButton('3')
        self.page_btn3.setFixedSize(25, 25)
        self.page_btn3.clicked.connect(self.button_click3)
        self.page_btn4 = QPushButton('4')
        self.page_btn4.setFixedSize(25, 25)
        self.page_btn4.clicked.connect(self.button_click4)
        self.page_btn5 = QPushButton('5')
        self.page_btn5.setFixedSize(25, 25)
        self.page_btn5.clicked.connect(self.button_click5)
        self.page_btn6 = QPushButton('6')
        self.page_btn6.setFixedSize(25, 25)
        self.page_btn6.clicked.connect(self.button_click6)

        self.page_label = QLabel('Текущяя страница: 1')

        self.button_click1()

        main_l = QVBoxLayout()
        h_l1 = QHBoxLayout()
        hl1_name = QHBoxLayout()
        h_l2 = QHBoxLayout()
        hl2_name = QHBoxLayout()
        h_l3 = QHBoxLayout()
        hl3_name = QHBoxLayout()
        hl_pages = QHBoxLayout()
        hl_page_label = QHBoxLayout()
        h_l1.addWidget(self.label1)
        h_l1.addWidget(self.label2)
        hl1_name.addWidget(self.name_label1)
        hl1_name.addWidget(self.name_label2)
        h_l2.addWidget(self.label3)
        h_l2.addWidget(self.label4)
        hl2_name.addWidget(self.name_label3)
        hl2_name.addWidget(self.name_label4)
        h_l3.addWidget(self.label5)
        h_l3.addWidget(self.label6)
        hl3_name.addWidget(self.name_label5)
        hl3_name.addWidget(self.name_label6)
        hl_pages.addWidget(self.page_btn1)
        hl_pages.addWidget(self.page_btn2)
        hl_pages.addWidget(self.page_btn3)
        hl_pages.addWidget(self.page_btn4)
        hl_pages.addWidget(self.page_btn5)
        hl_pages.addWidget(self.page_btn6)
        hl_page_label.addWidget(self.page_label)
        main_l.addLayout(h_l1)
        main_l.addLayout(hl1_name)
        main_l.addLayout(h_l2)
        main_l.addLayout(hl2_name)
        main_l.addLayout(h_l3)
        main_l.addLayout(hl3_name)
        main_l.addStretch()
        main_l.addLayout(hl_pages)
        main_l.addLayout(hl_page_label)
        self.setLayout(main_l)

    def button_click1(self):
        self.name_label1.setText('Над пропастью во ржи\nДж. Д. Сэллинджер\n800 руб.')
        self.name_label2.setText('1984\nДж. Оруэл\n1000 руб.')
        self.name_label3.setText('Преступление и наказание\nФ. Достоевский\n1500 руб.')
        self.name_label4.setText('Три товарища\nЭ. М. Ремарк\n400 руб.')
        self.name_label5.setText('Приключения Гекльберри Финна\nМ. Твен\n1200 руб.')
        self.name_label6.setText('Мёртвые Души\nН. Гоголь\n500 руб.')

        self.pixmap.load('book_pictures/TheCatcherInTheRye.jpg')
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/1984.jpg')
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/CrimeAndPunishment.jpg')
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/3Friends.jpg')
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load("book_pictures/adventure.jpeg")
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load("book_pictures/DeadSouls.jpg")
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 1')

    def button_click2(self):
        self.name_label1.setText('Кортик\nА. Рыбаков\n500 руб.')
        self.name_label2.setText('Чёрный Обелиск\nЭ. М. Ремарк\n800 руб.')
        self.name_label3.setText('Идиот\nФ. Достоевский\n1200 руб.')
        self.name_label4.setText('На западном фронте без перемен\nЭ. М. Ремарк\n900 руб.')
        self.name_label5.setText('Приключения Тома Соера\nМ. Твен\n350 руб.')
        self.name_label6.setText('Вий\nН. Гоголь\n700 руб.')

        self.pixmap.load('book_pictures/Kortik.jpg')
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/BlackObelisc.jpg')
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/Idiot.jpg')
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/AllQuite.jpg')
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/TomSoier.jpg')
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load("book_pictures/viy.jpg")
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 2')

    def button_click3(self):
        self.name_label1.setText('Зелёная миля\nС. Кинг\n400 руб.')
        self.name_label2.setText('Скотный двор\nДж. Оруэл\n950 руб.')
        self.name_label3.setText('Крестный отец\nМ. Пьюзо\n800 руб.')
        self.name_label4.setText('Десять негритят\nА. Кристи\n1000 руб.')
        self.name_label5.setText('Мастер и Маргарита\nМ. Булгаков\n550 руб.')
        self.name_label6.setText('Белый Бим Чёрное ухо\nГ. Троепольский\n200 руб.')

        self.pixmap.load('book_pictures/GreenMile.jpg')
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/SkotDvor.jpg')
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/father.jpg')
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/10niggers.jpg')
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/master.jpg')
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load("book_pictures/whiteBim.jpg")
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 3')

    def button_click4(self):
        self.name_label1.setText('Волшебник Изумрудного города\nА. Волков\n1000 руб.')
        self.name_label2.setText('451° по Фаренгейту\nР. Брэдбери\n900 руб.')
        self.name_label3.setText('Портрет Дориана Грея\nОскар Уайльд\n700 руб.')
        self.name_label4.setText('Маленький принц\nА. Экзюпери\n600 руб.')
        self.name_label5.setText('Анна Каренина\nЛ. Толстой\n400 руб.')
        self.name_label6.setText('Убить пересмешника\nХ. Ли\n1100 руб.')

        self.pixmap.load('book_pictures/magician.jpg')
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/451.jpg')
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/DorianGrey.jpg')
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/littleprince.jpg')
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/anna.jpg')
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load("book_pictures/kill.jpg")
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 4')

    def button_click5(self):
        self.name_label1.setText('Двенадцать стульев\nЕ. Петров\n250 руб.')
        self.name_label2.setText('Граф Монте-Кристо\nА. Дюма\n450 руб.')
        self.name_label3.setText('Великий Гэтсби\nФ. Фицджеральд\n1300 руб.')
        self.name_label4.setText('Евгений Онегин\nА. Пушкин\n750 руб.')
        self.name_label5.setText('Бойцовский Клуб\nЧ. Паланик\n500 руб.')
        self.name_label6.setText('Герой нашего времени\nМ. Лермонтов\n300 руб.')

        self.pixmap.load('book_pictures/12chairs.jpg')
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/monte-kristo.jpg')
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/gatsby.jpg')
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/onegin.jpg')
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/fightClub.jpg')
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load("book_pictures/hero.jpg")
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #A3C1DA}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #00000}')

        self.page_label.setText('Текущая страница: 5')

    def button_click6(self):
        self.name_label1.setText('Собачье сердце\nМ. Булгаков\n550 руб.')
        self.name_label2.setText('Старик и море\nЭ. Хемингуэй\n350 руб.')
        self.name_label3.setText('Горе от ума\nА. Грибоедов\n700 руб.')
        self.name_label4.setText('Фауст\nИ. Гете\n650 руб.')
        self.name_label5.setText('Обломов\nИ. Гончаров\n400 руб.')
        self.name_label6.setText('Сто лет одиночества\nГ. Маркес\n550 руб.')

        self.pixmap.load("book_pictures/dog'sHeart.jpg")
        scaled_pixmap1 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/grandAndSea.jpg')
        scaled_pixmap2 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/sad_from_knowledge.jpg')
        scaled_pixmap3 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/faust.jpg')
        scaled_pixmap4 = self.pixmap.scaled(150, 200)
        self.pixmap.load('book_pictures/oblomov.jpg')
        scaled_pixmap5 = self.pixmap.scaled(150, 200)
        self.pixmap.load("book_pictures/100years.jpg")
        scaled_pixmap6 = self.pixmap.scaled(150, 200)

        self.label1.setPixmap(scaled_pixmap1)
        self.label2.setPixmap(scaled_pixmap2)
        self.label3.setPixmap(scaled_pixmap3)
        self.label4.setPixmap(scaled_pixmap4)
        self.label5.setPixmap(scaled_pixmap5)
        self.label6.setPixmap(scaled_pixmap6)

        self.page_btn1.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn2.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn3.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn4.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn5.setStyleSheet('QPushButton {background-color: #00000}')
        self.page_btn6.setStyleSheet('QPushButton {background-color: #A3C1DA}')

        self.page_label.setText('Текущая страница: 6')


def main():
    app = QApplication([])
    win = AssortmentWin()
    win.show()
    app.exec()


if __name__ == '__main__':
    main()
